### ISSUE TITLE
[BUG] Backend Issue: Lacking EasyOCR and Cyclopts

### ISSUE THREAD

**Issue by LilAttacker** [UNLV-CS472-672/2024-F-GROUP1-Tabby#40]
# Lacking EasyOCR and Cyclopts

## Issue Description
When using "poe ci" an error popped up with mypy.

It appears a couple of libraries may not have been added to the poetry list.

## Reproduce

1. use "poe ci", it should appear.

#### What actually happened

![image](https://github.com/user-attachments/assets/fb49e691-a168-445b-813c-b6ece00b4001)

#### What is supposed to happen

Not that error.

# Source Code
![image](https://github.com/user-attachments/assets/89f962a9-2229-4b74-a267-4fe080bc453e)

Found in poetry.toml.

## Suggested Fixes
Someone who knows which library to add should add it.

I would do it, but I'm not concerned at the moment, I want to make a bug report and use these templates, and also I'm not sure if a specific version of these libraries is necessary.

**Comment by ederic-oytas** [comment]
Hi Daniel, I've tested `poe ci` with a fresh install, and there seem to be no problems here. It may be an issue with your installation.

I believe the following commands should cover this:

```bash
cd server
rm -f venv
python3 --version  # check that it's 3.12 installed
python3 -m venv ./venv
source ./venv/bin/activate  # ./venv/scripts/activate on windows
poetry install
```

**Comment by ederic-oytas** [comment]
By the way, this kind of error would've already been caught by Github Actions.

**Comment by LilAttacker** [comment]
You can actually see easyocr and cyclopts in my poetry dependencies image.

I just had to re-run poetry install to download and get it to work. Not sure why it didn't install the first time, but whatever.

Issue was not real.

**Comment by ederic-oytas** [comment]
Yes, it may be listed as a dependency, but it may not actually be installed. To see what's installed, you can use `pip freeze` to see all packages which are installed. Typically, you would run `poetry install` after a git pull.
