### ISSUE TITLE
[BUG] No Logs

### ISSUE THREAD

**Issue by LilAttacker** [UNLV-CS472-672/2024-F-GROUP1-Tabby#81]
# Server Lacks Logs

## Issue Description
There are no logs for the backend making it difficult to tell when certain functions are in use.

## Suggested Fixes
Add logs to display as certain processes are completed.

## Additional Notes
This would make it easier to see what is happening on the backend.

**Comment by jjyutm4532** [comment]
Hello, I tried to solve the issue.

This is what I did:

Add logging configuration and log messages to key functions in the server's main file to improve backend visibility.

You can review changes in this commit: https://github.com/jjyutm4532/UNLV-CS472-672-2024-F-GROUP1-Tabby-81/commit/99bd91a4e85566dbecc62df82732dc9baa008dac.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
