### ISSUE TITLE
[BUG] Author Misidentification

### ISSUE THREAD

**Issue by LilAttacker** [UNLV-CS472-672/2024-F-GROUP1-Tabby#84]
# ChatGPT Can't Say the Author

## Issue Description
It's not always possible for ChatGPT to correctly identify the author, but it still gives back something even in those cases. This causes bad results to be returned and used and also limit our total number of results.

#### What actually happened
Currently can give back incorrect author info which poisons our results.

#### What is supposed to happen
ChatGPT doesn't do that and we have some filter to check how confident ChatGPT is in its answer or something.

## Suggested Fixes
Either ignore this field or add a filter of some kind.

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modify the scan_cover function to handle cases where the author extraction has low confidence. We'll add a confidence threshold and only use the author in the Google Books API call if the confidence is above this threshold.

You can review changes in this commit: https://github.com/mnmnk43434/UNLV-CS472-672-2024-F-GROUP1-Tabby-84/commit/72896305bd996411cb8451568c6e0c1096cc0800.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
