### ISSUE TITLE
[BUG] ISBN Searching is Bad

### ISSUE THREAD

**Issue by LilAttacker** [UNLV-CS472-672/2024-F-GROUP1-Tabby#90]
# Cannot Search on ISBN Alone

## Issue Description
When searching with ISBN 13 or 10, results are bad or limited. Searching with more general terms and names gives better and more relevant results.

#### What actually happened
Can't search with ISBN 13 or 10 practically as results are too bad.

#### What is supposed to happen
Results should stay relevant no matter how we're searching as long as it remains valid.

## Suggested Fixes
Further filtering or backend adjustments.

**Comment by caesarx26** [comment]
When I was testing searching with isbn it seems to work good but I didn't test a lot I just used some harry potter books. What books could you not find for example or what did you try?

**Comment by LilAttacker** [comment]
I haven't tested it at all, I made this based on your description for #83. If something is wrong/incorrect, feel free to edit it and change it.

**Comment by LilAttacker** [comment]
Turns out I misunderstood. This issue doesn't exist.
